### ISSUE TITLE
TokenError: The code passed is incorrect or expired.

### ISSUE THREAD

**Issue by alphashuro** [johnstonbl01/clementinejs-fcc#13]
I'm trying to log in to the app but I'm getting 

```
TokenError: The code passed is incorrect or expired.
   at Strategy.OAuth2Strategy.parseErrorResponse (...\node_modules\passport-oauth2\lib\strategy.js:320:12)
   at Strategy.OAuth2Strategy._createOAuthError (...\node_modules\passport-oauth2\lib\strategy.js:367:16)
   at ...\node_modules\passport-oauth2\lib\strategy.js:166:45
   at ...\node_modules\passport-github\lib\strategy.js:77:16
   at ...\node_modules\oauth\lib\oauth2.js:195:7
   at passBackControl (...\node_modules\oauth\lib\oauth2.js:125:9)
   at IncomingMessage.<anonymous> (...\node_modules\oauth\lib\oauth2.js:143:7)
   at emitNone (events.js:85:20)
   at IncomingMessage.emit (events.js:179:7)
   at endReadableNT (_stream_readable.js:913:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any ideas regarding this?

**Comment by johnstonbl01** [comment]
Hi there! Can you tell me a bit more about your setup?
- Are you following the tutorial from the website, or just trying to install the app for the FCC exercises?
- Have you setup the .env files and registered with the GitHub API (as mentioned in the docs)?

**Comment by alphashuro** [comment]
I figured it out, I think it had something to do with an app that was trying to manage my passwords for me, it must have been causing the page to try to login multiple times unnecessarily. soon as I removed it everything was back to normal.

**Comment by johnstonbl01** [comment]
Great! Glad you got it working. :smile:
