### ISSUE TITLE
Error: socket hang up , my OAuth don't seem to work 

### ISSUE THREAD

**Issue by ooade** [johnstonbl01/clementinejs-fcc#5]
After going through the steps and running `node server.js` , it ran successfully but clicking the login button, this showed up

```
Error: socket hang up
    at Strategy.OAuth2Strategy._createOAuthError (/home/m4rhy0rh/workspace/project1/node_modules/passport-oauth2/lib/strategy.js:348:17)
    at /home/m4rhy0rh/workspace/project1/node_modules/passport-oauth2/lib/strategy.js:171:43
    at /home/m4rhy0rh/workspace/project1/node_modules/oauth/lib/oauth2.js:177:18
    at ClientRequest.<anonymous> (/home/m4rhy0rh/workspace/project1/node_modules/oauth/lib/oauth2.js:148:5)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketErrorListener (http.js:1547:9)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at SecurePair.<anonymous> (tls.js:1400:15)
    at SecurePair.EventEmitter.emit (events.js:95:17)
    at SecurePair.error (tls.js:1020:27)
    at EncryptedStream.CryptoStream._done (tls.js:705:22)
    at CleartextStream.read [as _read] (tls.js:496:24)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:301:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.EventEmitter.emit (events.js:117:20)
```

**Comment by johnstonbl01** [comment]
Hi there! A few questions:
- Are you using c9.io?
- Which instructions, specifically, did you follow?
- If you try setting up a new workspace and running through the steps again, do you get the error message again?
- Does this error occur every time you try to authenticate or just occasionally?

Thanks!

**Comment by ooade** [comment]
Actually I've started base-jumps with `yo angular:fullstack` but i got this message about clementineJs, so i decided to give it a try. I am not using c9.io because of the Memory issues. I followed the instructions given here https://github.com/johnstonbl01/clementinejs-fcc. The Error comes up only when authenticating. Thanks!

**Comment by marhyorh** [comment]
I figured it out. The error was in app/config/passport.js 
i changed
```
   clientID: configAuth.githubAuth.clientID,
   clientSecret: configAuth.githubAuth.clientSecret,
```
to 
```
   client_id: configAuth.githubAuth.clientID,
   client_secret: configAuth.githubAuth.clientSecret,
```

**Comment by johnstonbl01** [comment]
Glad you got it figured out!

Quote from e-mail message:

"I figured it out. The error was in app/config/passport.js 
i changed

   clientID: configAuth.githubAuth.clientID,
   clientSecret: configAuth.githubAuth.clientSecret,
to

   client_id: configAuth.githubAuth.clientID,
   client_secret: configAuth.githubAuth.clientSecret,"
