### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by pdewouters** [johnstonbl01/clementinejs-fcc#6]
Hi, any suggestions?

```
AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.
   at Strategy.OAuth2Strategy.authenticate (/home/ubuntu/workspace/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:126:25)
   at attempt (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at authenticate (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/ubuntu/workspace/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
   at /home/ubuntu/workspace/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:330:12)
   at next (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:271:10)
   at SessionStrategy.strategy.pass (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:325:9)
   at SessionStrategy.authenticate (/home/ubuntu/workspace/node_modules/passport/lib/strategies/session.js:71:10)
   at attempt (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:348:16)
   at authenticate (/home/ubuntu/workspace/node_modules/passport/lib/middleware/authenticate.js:349:7)
   at Layer.handle [as handle_request] (/home/ubuntu/workspace/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/ubuntu/workspace/node_modules/express/lib/router/index.js:312:13)
```

**Comment by johnstonbl01** [comment]
Hi there. Make sure the URI you've provided for the GitHub app registration matches your site URL _exactly_ (this includes `/`). If you're still having issues - hop in the Gitter chat and we can troubleshoot.

**Comment by pdewouters** [comment]
<img width="410" alt="screenshot 2015-11-15 18 31 19" src="https://cloud.githubusercontent.com/assets/30460/11170293/951f5d90-8bc7-11e5-97c4-3169e766b93e.png">

**Comment by pdewouters** [comment]
Ok, I figured it out. I had to add a trailing slash to the `APP_URL` setting in the `.env` file and restart the node server.
Thanks

**Comment by johnstonbl01** [comment]
Glad you got it figured out!
